"""New tables

Revision ID: 21156316dbbe
Revises: 9ca5901af374
Create Date: 2020-01-28 20:45:00.940634

"""
from alembic import op
import sqlalchemy as sa
import app.model_types


# revision identifiers, used by Alembic.
revision = '21156316dbbe'
down_revision = '9ca5901af374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('uuid', app.model_types.GUID(), nullable=False),
    sa.Column('user_id', app.model_types.GUID(), nullable=False),
    sa.Column('note_id', app.model_types.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['note.uuid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_project_uuid'), 'project', ['uuid'], unique=True)
    op.create_table('tag',
    sa.Column('uuid', app.model_types.GUID(), nullable=False),
    sa.Column('user_id', app.model_types.GUID(), nullable=False),
    sa.Column('note_id', app.model_types.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['note.uuid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_tag_uuid'), 'tag', ['uuid'], unique=True)
    op.create_table('task',
    sa.Column('uuid', app.model_types.GUID(), nullable=False),
    sa.Column('user_id', app.model_types.GUID(), nullable=False),
    sa.Column('note_id', app.model_types.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('swimlane', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['note.uuid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_task_uuid'), 'task', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_uuid'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_tag_uuid'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_project_uuid'), table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###
