"""cleanup

Revision ID: 9ca5901af374
Revises: a477f34dbaa4
Create Date: 2020-01-28 20:44:00.184324

"""
from alembic import op
import sqlalchemy as sa
import app.model_types


# revision identifiers, used by Alembic.
revision = '9ca5901af374'
down_revision = 'a477f34dbaa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('projects')
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.VARCHAR(128), nullable=True))
        batch_op.add_column(sa.Column('projects', sa.VARCHAR(128), nullable=True))

    # ### end Alembic commands ###
