"""Initial config

Revision ID: a477f34dbaa4
Revises:
Create Date: 2020-01-07 21:31:19.007718

"""

from alembic import op
import sqlalchemy as sa
import app.model_types


# revision identifiers, used by Alembic.
revision = "a477f34dbaa4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("uuid", app.model_types.GUID(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_user_uuid"), "user", ["uuid"], unique=True)
    op.create_table(
        "note",
        sa.Column("uuid", app.model_types.GUID(), nullable=False),
        sa.Column("tags", sa.String(), nullable=True),
        sa.Column("projects", sa.String(), nullable=True),
        sa.Column("user_id", app.model_types.GUID(), nullable=False),
        sa.Column("data", sa.String(), nullable=True),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column(
            "date",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("is_date", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("title"),
    )
    op.create_index(op.f("ix_note_uuid"), "note", ["uuid"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_note_uuid"), table_name="note")
    op.drop_table("note")
    op.drop_index(op.f("ix_user_uuid"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
