"""Added auto_save column to User table

Revision ID: ad68860179f2
Revises: 9bd71ed6ccff
Create Date: 2021-11-23 17:33:25.117589

"""
from alembic import op
import sqlalchemy as sa
import app.model_types


# revision identifiers, used by Alembic.
revision = 'ad68860179f2'
down_revision = '9bd71ed6ccff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_save', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('auto_save')

    # ### end Alembic commands ###
