"""Meta Table

Revision ID: ba1754afe110
Revises: 9ca5901af374
Create Date: 2020-01-29 23:02:35.360745

"""
from alembic import op
import sqlalchemy as sa
import app.model_types


# revision identifiers, used by Alembic.
revision = 'ba1754afe110'
down_revision = '9ca5901af374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta',
    sa.Column('uuid', app.model_types.GUID(), nullable=False),
    sa.Column('user_id', app.model_types.GUID(), nullable=False),
    sa.Column('note_id', app.model_types.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['note.uuid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_meta_uuid'), 'meta', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meta_uuid'), table_name='meta')
    op.drop_table('meta')
    # ### end Alembic commands ###
