"""Add vim_mode column to User table

Revision ID: vim_mode_001
Revises: ad68860179f2
Create Date: 2025-11-10 00:00:00.000000

"""

from alembic import op
import sqlalchemy as sa
import app.model_types


# revision identifiers, used by Alembic.
revision = "vim_mode_001"
down_revision = "ad68860179f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("vim_mode", sa.Boolean(), nullable=True, server_default="0")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("vim_mode")

    # ### end Alembic commands ###
